language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"

install:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libpthread-stubs0-dev ; fi
        - git clone --single-branch -b fastflow3 https://github.com/fastflow/fastflow.git
        - ln -s fastflow/ff ff
script:
        - cd tests
        - make
        - ./run_tests.sh
