language: cpp
compiler: gcc
install:
        - git clone https://github.com/fastflow/fastflow.git
        - ls
        - pwd
        - ln -s fastflow/ff ff
script:
        - cd tests
        - make
        - ./run_tests.sh
