language: cpp

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "falkenrambaldi-github" # the key of the org you chose at step #3


cache:
  directories:
  - '$HOME/.sonar/cache'

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
        - eval "${MATRIX_EVAL}"
install:
        - git clone --single-branch https://github.com/fastflow/fastflow.git
        - ln -s fastflow/ff ff
script:
        - mkdir build && cd build
        - cmake ..
        - make
        - ctest
        - cp ../sonar-project.properties .
		- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then build-wrapper-macosx-x86  --out-dir bw-output make clean all ; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then build-wrapper-linux-x86-64 --out-dir bw-output make clean all ; fi
        - sonar-scanner
