language: cpp
matrix:
  include:

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"


before_install:
        - eval "${MATRIX_EVAL}"
install:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libpthread-stubs0-dev ; fi
        - git clone --single-branch -b fastflow3 https://github.com/fastflow/fastflow.git
        - ln -s fastflow/ff ff
script:
        - cd tests
        - make
        - ./run_tests.sh
