language: cpp
compiler: gcc
install:
        - sudo apt-get install libpthread-stubs0-dev
        - git clone https://github.com/fastflow/fastflow.git
        - ln -s fastflow/ff ff
script:
        - cd tests
        - make
        - ./run_tests.sh
