# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: PiCo
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxygen/Doxyfile
    - GH_REPO_REF: github.com/alpha-unito/PiCo.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - cd $TRAVIS_BUILD_DIR/test
#  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR/Doxygen
  - chmod +x generateAndDeploy.sh
  - ./generateAndDeploy.sh
