# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Enable C++11 build
language: cpp

compiler:
  - gcc
  - clang

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - clang

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: PiCo
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxygen/Doxyfile
    - GH_REPO_REF: github.com/alpha-unito/PiCo.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - cd $TRAVIS_BUILD_DIR/test
  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR/Doxygen
  - chmod +x generateAndDeploy.sh
  - ./generateAndDeploy.sh
